### PR TITLE
update runtime

### LINKED ISSUE #10: this app uses a no longer supported runtime
When I run `flatpak update`, the following message shows up:

```
$ flatpak update
Looking for updates…
Info: org.gnome.Platform//3.36 is end-of-life, with reason:
   The GNOME 3.36 runtime is no longer supported as of February 13, 2021. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   io.github.Hexchat
Nothing to do.
```

### PR DESCRIPTION
**Pull request by dgcampea**
Fix #10

### CODE REVIEW

**Comment by TingPing** [comment]
You need to update these too:

- https://github.com/flathub/io.github.Hexchat.Plugin.Perl
- https://github.com/flathub/io.github.Hexchat.Plugin.OTR

**Comment by dgcampea** [comment]
> You need to update these too:
> 
>     * https://github.com/flathub/io.github.Hexchat.Plugin.Perl
https://github.com/flathub/io.github.Hexchat.Plugin.Perl/pull/2 depends on this PR for libcanberra

>     * https://github.com/flathub/io.github.Hexchat.Plugin.OTR
can't get it to build after updating

**Comment by TingPing** [comment]
> can't get it to build after updating

Do you have more details?

**Comment by dgcampea** [comment]
> > can't get it to build after updating
> 
> Do you have more details?

Fails with:
```
[...]
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: src/.libs/otr_la-otr_ops.o:/run/build/hexchat-otr/src/hexchat_otr.h:58: multiple definition of `lvls'; src/.libs/otr_la-otr_key.o:/run/build/hexchat-otr/src/hexchat_otr.h:58: first defined here
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: src/.libs/otr_la-otr_util.o:/run/build/hexchat-otr/src/hexchat_otr.h:58: multiple definition of `lvls'; src/.libs/otr_la-otr_key.o:/run/build/hexchat-otr/src/hexchat_otr.h:58: first defined here
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: src/.libs/otr_la-hexchat_otr.o:/run/build/hexchat-otr/src/hexchat_otr.h:58: multiple definition of `lvls'; src/.libs/otr_la-otr_key.o:/run/build/hexchat-otr/src/hexchat_otr.h:58: first defined here
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: src/.libs/otr_la-hexchat-formats.o:/run/build/hexchat-otr/src/hexchat_otr.h:58: multiple definition of `lvls'; src/.libs/otr_la-otr_key.o:/run/build/hexchat-otr/src/hexchat_otr.h:58: first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:499: otr.la] Error 1
make[1]: Leaving directory '/run/build/hexchat-otr'
make: *** [Makefile:394: all] Error 2
Error: module hexchat-otr: Child process exited with code 2
```

**Comment by TingPing** [comment]
Can you build git master of https://github.com/TingPing/hexchat-otr?

**Comment by dgcampea** [comment]
> Can you build git master of https://github.com/TingPing/hexchat-otr?

Had to remove config-opts from io.github.Hexchat.Plugin.OTR since `--disable-static` doesn't exist for meson buildsystem but still fails.
```
Configuring config.h using configuration
Found pkg-config: /usr/bin/pkg-config (1.7.3)
Run-time dependency glib-2.0 found: YES 2.64.6
Run-time dependency libotr found: YES 4.1.1
Found CMake: /usr/bin/cmake (3.20.0)
Run-time dependency hexchat-plugin found: NO (tried pkgconfig and cmake)

../meson.build:48:0: ERROR: Dependency "hexchat-plugin" not found, tried pkgconfig and cmake

A full log can be found at /run/build/hexchat-otr/_flatpak_build/meson-logs/meson-log.txt
Error: module hexchat-otr: Child process exited with code 1
```

**Comment by hfiguiere** [comment]
> > > can't get it to build after updating
> > 
> > 
> > Do you have more details?
> 
> Fails with:
> 
> ```
> [...]
> /usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: src/.libs/otr_la-otr_ops.o:/run/build/hexchat-otr/src/hexchat_otr.h:58: multiple definition of `lvls'; src/.libs/otr_la-otr_key.o:/run/build/hexchat-otr/src/hexchat_otr.h:58: first defined here
> /usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: src/.libs/otr_la-otr_util.o:/run/build/hexchat-otr/src/hexchat_otr.h:58: multiple definition of `lvls'; src/.libs/otr_la-otr_key.o:/run/build/hexchat-otr/src/hexchat_otr.h:58: first defined here
> /usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: src/.libs/otr_la-hexchat_otr.o:/run/build/hexchat-otr/src/hexchat_otr.h:58: multiple definition of `lvls'; src/.libs/otr_la-otr_key.o:/run/build/hexchat-otr/src/hexchat_otr.h:58: first defined here
> /usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: src/.libs/otr_la-hexchat-formats.o:/run/build/hexchat-otr/src/hexchat_otr.h:58: multiple definition of `lvls'; src/.libs/otr_la-otr_key.o:/run/build/hexchat-otr/src/hexchat_otr.h:58: first defined here
> collect2: error: ld returned 1 exit status
> make[1]: *** [Makefile:499: otr.la] Error 1
> make[1]: Leaving directory '/run/build/hexchat-otr'
> make: *** [Makefile:394: all] Error 2
> Error: module hexchat-otr: Child process exited with code 2
> ```

This is typical of a variable not declared `extern` in a header. With more recent gcc, the compiler / linked no longer deduplicate it. The new runtime brings a new gcc.

**Comment by TingPing** [comment]
I do believe the compile error is fixed in git.

As for failing to find hexchat-plugin.pc the plugin likely needs to set `prepend-pkg-config-path`

**Comment by dgcampea** [comment]
> I do believe the compile error is fixed in git.
> 
> As for failing to find `hexchat-plugin.pc` the plugin's manifest likely needs to set `prepend-pkg-config-path`
> 
> (or maybe we need to not cleanup that file here?)

odd, because I remember it builds with the outdated runtime (and the cleanup section hasn't changed)

**Comment by TingPing** [comment]
> odd, because I remember it builds with the outdated runtime (and the cleanup section hasn't changed)

I don't think the previous autotools build system checked pkg-config at all for hexchat's installed header.

**Comment by dgcampea** [comment]
Leaving the pkgconfig files and adding other changes, it gets to:
```
/app/extensions/OTR/include/libotr/instag.h:71:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
   71 | otrl_instag_t otrl_instag_get_new();
      | ^~~~~~~~~~~~~
[7/7] Linking target src/otr.so
[0/1] Installing files.
Installing src/otr.so to /home/dgc/.config/hexchat/addons
install: cannot stat 'io.github.Hexchat.Plugin.OTR.metainfo.xml': No such file or directory
Error: module hexchat-otr: Child process exited with code 1
```

**Comment by TingPing** [comment]
> Installing src/otr.so to /home/dgc/.config/hexchat/addons

`"config-opts": ["-Dlocal_install=false"]`

**Comment by dgcampea** [comment]
Opened https://github.com/flathub/io.github.Hexchat.Plugin.OTR/pull/3

**Comment by TingPing** [comment]
>  Edit: currently fails since it depends on the .pc file that gets cleaned up. This PR changes that.

I don't see that change in this PR?

Otherwise seems ready to merge, thanks a lot.

**Comment by dgcampea** [comment]
> I don't see that change in this PR?

My bad, forgot to commit it.

**Pull request merged**
